config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"

  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'

  # NOTE: we need build path without resources and use *id instead :id becouse
  # rails escape slash in url helpers, eg repo_path(repo) renders as user_name%2Frepo_name
  # instead user_name/repo_name
  scope :repos do
    scope ":owner_id/:repo_id", as: :repo do
      resources :branches, only: [] do
        resources :files, only: :index
        get "files/*id", to: "files#show", as: :file, constraints: {id: /.*/}
      end
    end

    get ":owner_id/:repo_id", to: "repos#show", as: :repo
    get "/", to: "repos#index", as: :repos
  end

  namespace :profile do
    root to: 'home#index'

    resources :billing, only: [:index] do
      resource :subscription, only: [:new, :create]
    end
  end

  resources :jobs, only: [:show]
  resources :builds, only: :create
  resources :repo_syncs, only: [:create]
  resources :repo_activations, only: [:update, :destroy]
  resources :github_events, only: [:create]

  get "/*id", to: 'pages#show', as: :page, format: false
  root 'home#index'

  match '*path', to: 'application#catch_404', via: :all
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  belongs_to :owner
  belongs_to :activator, class_name: "User", foreign_key: :activated_by
  has_many :memberships
  has_many :users, through: :memberships
  has_many :branches
  has_one :default_branch, -> { where(default: true) }, class_name: 'Branch'

  validates :name, presence: true
  validates :owner, presence: true
  validates :github_id, uniqueness: true, presence: true

  scope :low_activity, -> do
    joins(branches: :builds)
      .where("builds.updated_at <= '#{30.days.ago}'")
      .where.not('builds.state' => :pending)
  end

  def self.active(value = true)
    where(active: value)
  end

  def self.find_or_create_with(attributes)
    repo = where(github_id: attributes[:github_id]).first_or_initialize
    repo.update(attributes)
    repo
  end

  def full_name
    @full_name ||= "#{owner.name}/#{name}"
  end

  def activate(user)
    update(active: true, activator: user) unless active?
  end

  def deactivate
    update(active: false, activator: nil) if active?
  end

  def scm_url
    "https://#{activator.access_token}:@github.com/#{full_name}.git"
  end

  def path
    @path ||= Pathname.new(ENV.fetch('SHIPLIX_BUILDS_PATH', Rails.root.join("tmp/builds"))).join(full_name)
  end

  def to_param
    name
  end

  def public?
    !private?
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    scope = current_user.
      repos.
      joins(:owner).
      order("owners.name asc, repos.name asc").
      preload(:owner, :default_branch)

    @repos = scope.active.to_a +
             scope.active(false).where(memberships: {admin: true}).to_a

    # preload memberships for pundit policy
    current_user.memberships.to_a
  end

  def show
    authorize current_repo, :show?

    title_variables[:repo] = @repo.full_name

    @branch = @repo.default_branch

    @changesets = ChangesetsFinder.new(@branch).call if @branch
  end
end

app/views/repos/_changesets.html.haml
.timeline.timeline-right
  - changesets.each do |month, slice|
    .timeline-item.timeline-main
      .timeline-date= month.strftime("%B")

    - slice.each do |date, slice2|
      .timeline-item.timeline-item-right
        .timeline-item-info{title: date}
          = time_ago_in_words(date)
          ago

        - slice2.each do |is_new, changesets|
          .timeline-item-icon
            %i.fa{class: is_new ? "fa-plus" : "fa-exchange"}

          .timeline-item-content
            .timeline-heading
            .timeline-body
              .panel.panel-default
                .panel-body
                  .list-group.border-bottom
                    - changesets.each do |changeset|
                      %li.list-group-item
                        - if changeset.grade_before.present?
                          .timeline-marks
                            .progress-timeline-arrow
                              %i.fa.fa-arrow-up
                            %div
                              = grade_badge(changeset.grade_after)
                            %div
                              = grade_badge(changeset.grade_before)
                        - else
                          .timeline-marks.new-mark
                            = grade_badge(changeset.grade_after)

                        .timeline-class-name
                          %h3
                            = link_to changeset.path,
                                      repo_branch_file_url(@repo.owner, @repo, @repo.default_branch, changeset.path)
            .timeline-footer.timeline-footer-without-padding

app/views/repos/_repo.html.haml
-# TODO: move to controller, remove n+1 by preloading, will denormalize latest successful push-build?
- build = repo.default_branch.try(:recent_push_build) || Builds::Push.new if repo.active?

%tr
  %td
    - if repo.active?
      %h3
        = gpa_badge(build.gpa)

  %td
    %h3
      - if repo.active?
        = link_to repo.full_name, repo_url(repo.owner, repo)
      - else
        = repo.full_name

  %td
    - if repo.active?
      %h3
        = build.smells_count

  %td
    - if policy(repo).activate?
      %label.switch
        - if repo.active?
          = check_box_tag "#{repo.id}_switch",
                          1,
                          true,
                          data: {remote: true,
                                 url: repo_activation_url(id: repo.id),
                                 method: 'delete',
                                 confirm: 'Are you sure?'},
                          class: 'js-repo-deactivate'
        - else
          = check_box_tag "#{repo.id}_switch",
                          1,
                          false,
                          data: {remote: true,
                                 url: repo_activation_url(id: repo.id),
                                 method: 'put'},
                          class: 'js-repo-activate'
        %span

app/views/repos/index.html.haml
- breadcrumb :repos

- content_for(:header_icon, 'fa-arrow-circle-o-left')

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        .panel-title-box
          %h3 Repositories
          %span Repositories list

        %ul.panel-controls
          %li
            %a.panel-fullscreen{href: '#'}
              %i.fa.fa-expand
          %li
            = link_to repo_syncs_url, remote: true, method: :post, class: 'js-refresh-repos' do
              %i.fa.fa-refresh

      .panel-body.panel-body-table
        - if @repos.present?
          .table-responsive
            %table.table.table-bordered.table-striped
              %thead
                %tr
                  %th{style: 'width: 100px'} Marks
                  %th Repository name
                  %th{style: 'width: 100px'} Smells
                  %th{style: 'width: 75px'} Status
              %tbody
                = render(@repos)
        - else
          There is no repositories loaded yet

app/views/repos/show.html.haml
- breadcrumb :repo, @repo

.row
  .col-md-12
    = render "changesets", changesets: @changesets if @changesets