config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"

  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'

  # NOTE: we need build path without resources and use *id instead :id becouse
  # rails escape slash in url helpers, eg repo_path(repo) renders as user_name%2Frepo_name
  # instead user_name/repo_name
  scope :repos do
    scope ":owner_id/:repo_id", as: :repo do
      resources :branches, only: [] do
        resources :files, only: :index
        get "files/*id", to: "files#show", as: :file, constraints: {id: /.*/}
      end
    end

    get ":owner_id/:repo_id", to: "repos#show", as: :repo
    get "/", to: "repos#index", as: :repos
  end

  namespace :profile do
    root to: 'home#index'

    resources :billing, only: [:index] do
      resource :subscription, only: [:new, :create]
    end
  end

  resources :jobs, only: [:show]
  resources :builds, only: :create
  resources :repo_syncs, only: [:create]
  resources :repo_activations, only: [:update, :destroy]
  resources :github_events, only: [:create]

  get "/*id", to: 'pages#show', as: :page, format: false
  root 'home#index'

  match '*path', to: 'application#catch_404', via: :all
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
    return not_found unless current_branch
    authorize current_repo, :show?

    @files = FilesFinder.new(current_branch, page: params.fetch(:page, 1), per_page: 20)

    title_variables[:repo] = current_repo.full_name
  end

  def show
    return not_found unless current_branch
    authorize current_repo, :show?

    @file = current_branch.files.find_by!(path: params.require(:id))

    @file.content = api.file_contents(current_repo.full_name,
                                      @file.path,
                                      current_branch.recent_push_build.revision)

    title_variables[:repo] = current_repo.full_name
    title_variables[:name] = @file.path
  end
end

app/views/files/_code.html.haml
- smells = render(template: "smells/_smells", formats: :json, locals: {smells: file.smells.decorate})

%pre
  %code{class: 'ruby', data: {smells: smells}}
    = preserve do
      = file.content

app/views/files/_files.html.haml
- cache [branch, files] do
  .panel-body.panel-body-table
    - if files.any?
      .table-responsive
        %table.table.table-bordered.table-striped
          %thead
            %tr
              %th{style: 'width: 90px'} Marks
              %th Name
              %th{style: 'width: 90px'} Complexity
              %th{style: 'width: 90px'} Duplication
              %th{style: 'width: 90px'} LOC
              %th{style: 'width: 90px'} Smells
          %tbody
            - files.each do |file|
              %tr
                %td
                  = grade_badge(file.grade)
                %td
                  %h4
                    = link_to file.path, repo_branch_file_url(repo.owner, repo, branch, file)
                %td
                  %h3= file.metrics['complexity'].to_i
                %td
                  %h3= file.metrics['duplication'].to_i
                %td
                  %h3= file.metrics['loc']
                %td
                  %h3= file.smells_count
    - else
      There is no analyzed files yet.

  .panel-footer
    = will_paginate files, renderer: BootstrapPagination::Rails

app/views/files/index.html.haml
- breadcrumb :files, @repo, @branch

- content_for(:header_icon, 'fa-file-text-o')

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        .panel-title-box
          %h3 Source Files

        %ul.panel-controls
          %li{style: 'width: 200px;'}
            = select_tag "change_branch",
                         options_from_collection_for_select(@repo.branches, :name, :name, @branch.name),
                         data: {url: repo_branch_files_url(@repo.owner, @repo, ":branch")},
                         class: "form-control js-change-branch"
          %li{style: 'width: 300px;'}
            %input.form-control.ui-autocomplete-input{placeholder: 'Search by name...', autocomplete: 'off'}
          %li
            %a.panel-fullscreen{href: '#'}
              %i.fa.fa-expand
          - if policy(@repo).manage?
            %li
              = link_to builds_url(repo_id: @repo.id, branch: @branch.name),
                        remote: true, method: :post, class: 'js-build-repo' do
                %i.fa.fa-refresh

      = render "files", files: @files, branch: @branch, repo: @repo

app/views/files/show.html.haml
- breadcrumb :file, @repo, @file

- content_for(:header_icon, 'fa-file-code-o')

.row
  .col-md-12
    .panel-heading
      = render "smells/badges", file: @file

    .panel.panel-warning
      .panel-heading
        %h3.panel-title= @file.path

        %ul.panel-controls
          %li
            %a.panel-fullscreen{href: "#"}
              %i.fa.fa-expand
          %li
            %a.panel-collapse{href: ""}
              %i.fa.fa-angle-down

        .panel-body
          = render "files/code", file: @file